// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Project struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ProjectsUser struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

type Task struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ProjectID uuid.UUID
}

type TimeRecord struct {
	ID        uuid.UUID
	StartTime time.Time
	EndTime   time.Time
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	TaskID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	HashedPassword string
	Name           string
	Email          string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
