-- +goose Up
CREATE TABLE tasks(
    id UUID PRIMARY KEY UNIQUE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE IF EXISTS tasks;