// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: time_records.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTimeRecord = `-- name: CreateTimeRecord :one
INSERT INTO time_records (
    id,
    name,
    start_time,
    end_time,
    task_id,
    project_id
) VALUES (
             $1, $2, $3, $4, $5, $6
         )
RETURNING id, start_time, end_time, name, created_at, updated_at, task_id, project_id
`

type CreateTimeRecordParams struct {
	ID        uuid.UUID
	Name      string
	StartTime time.Time
	EndTime   time.Time
	TaskID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) CreateTimeRecord(ctx context.Context, arg CreateTimeRecordParams) (TimeRecord, error) {
	row := q.db.QueryRowContext(ctx, createTimeRecord,
		arg.ID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.TaskID,
		arg.ProjectID,
	)
	var i TimeRecord
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskID,
		&i.ProjectID,
	)
	return i, err
}

const deleteTimeRecord = `-- name: DeleteTimeRecord :exec
DELETE FROM time_records
WHERE id = $1
`

func (q *Queries) DeleteTimeRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTimeRecord, id)
	return err
}

const getAllTimeRecords = `-- name: GetAllTimeRecords :many
SELECT id, start_time, end_time, name, created_at, updated_at, task_id, project_id FROM time_records
`

func (q *Queries) GetAllTimeRecords(ctx context.Context) ([]TimeRecord, error) {
	rows, err := q.db.QueryContext(ctx, getAllTimeRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeRecord
	for rows.Next() {
		var i TimeRecord
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeRecord = `-- name: GetTimeRecord :one
SELECT id, start_time, end_time, name, created_at, updated_at, task_id, project_id FROM time_records
WHERE id = $1
`

func (q *Queries) GetTimeRecord(ctx context.Context, id uuid.UUID) (TimeRecord, error) {
	row := q.db.QueryRowContext(ctx, getTimeRecord, id)
	var i TimeRecord
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskID,
		&i.ProjectID,
	)
	return i, err
}

const listTimeRecordsForProject = `-- name: ListTimeRecordsForProject :many
SELECT id, start_time, end_time, name, created_at, updated_at, task_id, project_id FROM time_records
WHERE project_id = $1
ORDER BY created_at
`

func (q *Queries) ListTimeRecordsForProject(ctx context.Context, projectID uuid.UUID) ([]TimeRecord, error) {
	rows, err := q.db.QueryContext(ctx, listTimeRecordsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeRecord
	for rows.Next() {
		var i TimeRecord
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeRecordsForTask = `-- name: ListTimeRecordsForTask :many
SELECT id, start_time, end_time, name, created_at, updated_at, task_id, project_id FROM time_records
WHERE task_id = $1
ORDER BY created_at
`

func (q *Queries) ListTimeRecordsForTask(ctx context.Context, taskID uuid.UUID) ([]TimeRecord, error) {
	rows, err := q.db.QueryContext(ctx, listTimeRecordsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeRecord
	for rows.Next() {
		var i TimeRecord
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeRecordsForUser = `-- name: ListTimeRecordsForUser :many
SELECT tr.id, tr.start_time, tr.end_time, tr.name, tr.created_at, tr.updated_at, tr.task_id, tr.project_id
FROM time_records AS tr
JOIN projects_users AS pu ON tr.project_id = pu.project_id
WHERE pu.user_id = $1
ORDER BY tr.created_at
`

func (q *Queries) ListTimeRecordsForUser(ctx context.Context, userID uuid.UUID) ([]TimeRecord, error) {
	rows, err := q.db.QueryContext(ctx, listTimeRecordsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeRecord
	for rows.Next() {
		var i TimeRecord
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeRecord = `-- name: UpdateTimeRecord :one
UPDATE time_records
SET
    name = $2,
    start_time = $3,
    end_time = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, start_time, end_time, name, created_at, updated_at, task_id, project_id
`

type UpdateTimeRecordParams struct {
	ID        uuid.UUID
	Name      string
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) UpdateTimeRecord(ctx context.Context, arg UpdateTimeRecordParams) (TimeRecord, error) {
	row := q.db.QueryRowContext(ctx, updateTimeRecord,
		arg.ID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
	)
	var i TimeRecord
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskID,
		&i.ProjectID,
	)
	return i, err
}
